apiVersion: v1
kind: Namespace
metadata:
  name: ns2
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: foo-com-external-gateway-class
spec:
  controllerName: foo.com/external-gateway-class
  description: Create an external load balancer
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: bar-com-internal-gateway-class
spec:
  controllerName: bar.baz/internal-gateway-class
  description: Create an internal load balancer
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: demo-gateway-1
  namespace: default
spec:
  gatewayClassName: foo-com-external-gateway-class
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: demo-gateway-2
  namespace: ns2
spec:
  gatewayClassName: bar-com-internal-gateway-class
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: demo-httproute-1
  namespace: default
spec:
  parentRefs:
  - kind: Gateway
    name: demo-gateway-1
  hostnames:
  - "demo.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /example
    backendRefs:
    - name: demo-svc
      port: 80
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: demo-httproute-2
  namespace: default
spec:
  parentRefs:
  - kind: Gateway
    name: demo-gateway-1
  hostnames:
  - "example.com"
  - "example2.com"
  - "example3.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /example
    backendRefs:
    - name: demo-svc
      port: 80
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: demo-httproute-3
  namespace: default
spec:
  parentRefs:
  - kind: Gateway
    name: demo-gateway-1
  hostnames:
  - "demo.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /example
    backendRefs:
    - name: demo-svc
      port: 80
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: demo-httproute-3
  namespace: ns2
spec:
  parentRefs:
  - kind: Gateway
    name: demo-gateway-2
  hostnames:
  - "example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /example
    backendRefs:
    - name: demo-svc
      port: 80
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: demo-httproute-4
  namespace: ns2
spec:
  parentRefs:
  - kind: Gateway
    name: demo-gateway-1
    namespace: default
  hostnames:
  - "demo.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /example
    backendRefs:
    - name: demo-svc
      port: 80
---
apiVersion: bar.com/v1
kind: TimeoutPolicy
metadata:
  name: demo-timeout-policy-1
spec:
  targetRef:
    group: "gateway.networking.k8s.io"
    kind: GatewayClass
    name: foo-com-external-gateway-class
  default:
    sampleField: "hello"
---
apiVersion: foo.com/v1
kind: RetryOnPolicy
metadata:
  name: demo-retry-policy-1
  namespace: default
spec:
  targetRef:
    group: "gateway.networking.k8s.io"
    kind: Gateway
    name: demo-gateway-1
  default:
    sampleField: "hello"
---
apiVersion: baz.com/v1
kind: TLSMinimumVersionPolicy
metadata:
  name: demo-tls-min-version-policy-1
  namespace: default
spec:
  targetRef:
    group: "gateway.networking.k8s.io"
    kind: HTTPRoute
    name: demo-httproute-1
  default:
    sampleField: "hello"
---
apiVersion: foo.com/v1
kind: RetryOnPolicy
metadata:
  name: demo-retry-policy-2
  namespace: default
spec:
  targetRef:
    group: "gateway.networking.k8s.io"
    kind: HTTPRoute
    name: demo-httproute-2
  default:
    sampleField: "hello"
---
apiVersion: foo.com/v1
kind: HealthCheckPolicy
metadata:
  name: demo-health-check-1
  namespace: default
spec:
  targetRef:
    group: "gateway.networking.k8s.io"
    kind: Gateway
    name: demo-gateway-1
  default:
    sampleField: "hello"
---
apiVersion: baz.com/v1
kind: TLSMinimumVersionPolicy
metadata:
  name: demo-tls-min-version-policy-2
  namespace: ns2
spec:
  targetRef:
    group: "gateway.networking.k8s.io"
    kind: Gateway
    name: demo-gateway-2
  default:
    sampleField: "hello"
---
